# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test & Build Docker Container

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          # skapar variabel
          echo "::set-env name=SHORT_SHA::$(echo ${GITHUB_SHA::7})"
          echo "::set-env name=BRANCH::$(echo ${GITHUB_REF##*/})"
      - name: Concatenate environment varibles
        run: |
          echo "::set-env name=IMAGE_TAGS::${SHORT_SHA}"
          #skapar variabel för repositopry och unika commit id
        # måste göra en checkout för att klona repo för att komma åt filen docker. Docker ger i sin tur angivna instruktioner.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test, Build & Publish Docker image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          dockerfile: tests/Dockerfile
          #secrets är en encrypted variabel sparad i github. Konfigurerad med docker inlog/pw
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'
          image_name: '${{ secrets.DOCKER_HUB_USERNAME }}/meetups-assignment-tests'
          image_tag: '${{ env.IMAGE_TAGS }}'
